#release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bugs 🛠
      labels:
        - bug
        - hotfix
    - title: New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Other Changes
      labels:
        - "*"
