name: Build

on:
  push:
    branches:
      - feature/*
      - main
    tags:
      - v*

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

  workflow_dispatch:

jobs:
  publish_structurizr:
    name: Build Structurizr
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') )
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - context: ./structurizr/
            dockerfile: ./structurizr/Dockerfile
            name: gooten.azurecr.io/structurizr

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GOOTEN_DOCKER_REGISTRY_PROD_LOGIN_SERVER }}
          username: ${{ secrets.GOOTEN_DOCKER_REGISTRY_PROD_USERNAME }}
          password: ${{ secrets.GOOTEN_DOCKER_REGISTRY_PROD_PASSWORD }}

      - name: Merge PR with Base
        if: github.event_name == 'pull_request'
        run: |
          git fetch
          git checkout ${{ GITHUB.BASE_REF }}
          git merge origin/${{GITHUB.HEAD_REF }}

      - name: Extract metadata (tag, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.name }}

      - name: Push container image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.name }}:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy_structurizr:
    needs:
      - publish_structurizr
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
